## For testing provenance functions here
#!/bin/bash
#Exit immediately if any command returns a non-zero (error) status.#
set -e
#Make a pipeline (e.g. cmd1 | cmd2) fail if any command in it fails.
set -o pipefail

# -----------------------------------------------------------------------------
# Test script for provenance_functions_v2.sh
# -----------------------------------------------------------------------------
# This script initializes provenance metadata, then adds relationships
# using data that could come from analysis_document.json.
#

# --- Environment setup --------------------------------------------------------
export PYTHON=python3
export APP_NAME="test_prov"
export _tapisJobUUID="test-job-uuid-001"

# --- Source provenance functions ---------------------------------------------
source ./provenance_functions_v2.sh

# -----------------------------------------------------------------------------
# Step 1. Initialize metadata
# -----------------------------------------------------------------------------
echo ">>> Initializing provenance metadata"
initProvenance

# -----------------------------------------------------------------------------
# Step 2. Simulate reading from analysis_document.json
# -----------------------------------------------------------------------------
# Normally, you would parse this dynamically from the JSON file.
# For now, we extract a few example values for testing.
# ENTITY="vdjserver:app:outputs:vdjpipe"
# ACTIVITY="vdjserver:activity:vdjpipe"
# SOURCE_ENTITY="airr:Repertoire:1fea9299-a371-4c03-9dcc-26c88a884e2c"
# AGENT="vdjserver:agent:test"

# ANALYSIS_JSON="analysis_document.json"
# ENTITY=$(jq -r '.[0].value | .isGeneratedBy | keys[0]' $ANALYSIS_JSON)
# ACTIVITY=$(jq -r '.[0].value.activity | keys[0]' $ANALYSIS_JSON)
# SOURCE_ENTITY=$(jq -r '.[0].value.uses | keys[0]' $ANALYSIS_JSON)
# AGENT="vdjserver:agent:test"
# -----------------------------------------------------------------------------
# Step 3. Add provenance relations
# -----------------------------------------------------------------------------
# echo ">>> Adding provenance relationships"



# # Example: output was generated by the vdjpipe activity
# wasGeneratedBy "$ENTITY" "$ACTIVITY"

# # Example: output was derived from the input repertoire entity
# wasDerivedFrom "$ENTITY" "$SOURCE_ENTITY"

#just a test
wasDerivedFrom "1" "2"
# # Example: activity used an input repertoire
# used "$ACTIVITY" "$SOURCE_ENTITY"

# # Example: activity was associated with an agent (user, system, etc.)
# wasAssociatedWith "$ACTIVITY" "$AGENT"

# # Example: entity was attributed to an agent
# wasAttributedTo "$ENTITY" "$AGENT"

# -----------------------------------------------------------------------------
# Step 4. Display resulting metadata
# -----------------------------------------------------------------------------
echo
echo ">>> Final process_metadata.json contents:"
cat process_metadata.json | jq .

echo
echo " Test provenance run completed successfully."
